markdown: rdiscount
permalink: /:year/:month/:day/:title.html
baseurl: /blog
url: 
# 参见http://jekyllrb.com/docs/variables/#site-variables
lsi: false
highlighter: true
safe: true
auto: true 
encoding: utf-8

# 参见http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "page:num"

# presonal config
title: 一个人の童话
description: karchi's Blog, 但其实真实命运很少写得这么吸引
feed: /atom.xml

author: karchi
author_info: <a href="/about.html">karchi</a>

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
