markdown: kramdown
permalink: /:year/:month/:day/:title.html
baseurl: /blog
url: 
# 参见http://jekyllrb.com/docs/variables/#site-variables
lsi: false
highlighter: pygments
safe: true
auto: true 
encoding: utf-8

# 参见http://jekyllrb.com/docs/pagination/
paginate: 15
paginate_path: "page:num"

# presonal config
title: karchi的博客
description: karchi's Blog,关注投资、计算机、阅读……
feed: /atom.xml

author: karchi
author_info: <a href="/about.html">karchi</a>

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
